title:  "Cashews & Screws"
description:
author:
  name: "Alex, Ashley and Apollo"

menu:
- {name: 'Recipes', file: 'facts.html'}
- {name: 'Projects', file: 'resources.html'}
- {name: 'Outreach', file: 'sample-posts.html'}
- {name: 'Science', file: 'documentation.html'}
- {name: 'About', file: 'about.html'}
- {name: 'Contact', file: 'contact.html'}

social:
- {icon: 'instagram', link: 'https://instagram.com/cashewsandscrews'}
- {icon: 'envelope', link: 'mailto:cashewsandscrews@gmail.com'}
